---
title: "Test TILPRED R Notebook"
output: html_notebook
---

Manually install TILPRED and required packages, or alternatively packrat::restore()
```{r eval=F}
install.packages(c("doParallel","doRNG"))
install.packages("BiocManager")
library(BiocManager)
BiocManager::install("AUCell")
BiocManager::install("SingleCellExperiment")
install.packages("devtools")
install_github("carmonalab/TILPRED")
#library(packrat)
#packrat::restore()
```



Load SingleCellExperiment and TILPRED libraries
```{r message=FALSE}
library(SingleCellExperiment)
library(TILPRED)
```


Import example CD8 tumor-infiltrating T-cell dataset from NCBI GEO (TPM matrix, Series GSE86028, Singer et al 2016)
```{r Import data}
fn="tpm_matrix.csv.gz"
download.file("ftp://ftp.ncbi.nlm.nih.gov/geo/series/GSE86nnn/GSE86028/suppl/GSE86028_TILs_sc_wt_mtko.tpm.log2.txt.gz",paste0("input/",fn))
m <- read.csv(paste0("input/",fn),sep=" ")
m[1:5,1:5]
```


Create SingleCellExperiment Object
```{r}
sce <- SingleCellExperiment(assays = list(logcounts = as.matrix(m)))
sce
```

Run TILPRED and show output summary 
```{r}
x <- predictTilState(sce)
table(x$predictedState)
head(x$stateProbabilityMatrix)
```


```{r}
sessionInfo()
```

